/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.ITimer;

public class ExampleStatemachine implements IExampleStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private boolean begin;
		
		public void raiseBegin() {
			begin = true;
		}
		
		private boolean enterTrap;
		
		public void raiseEnterTrap() {
			enterTrap = true;
		}
		
		private boolean white;
		
		public void raiseWhite() {
			white = true;
		}
		
		private boolean black;
		
		public void raiseBlack() {
			black = true;
		}
		
		private long lightTime;
		
		public long getLightTime() {
			return lightTime;
		}
		
		public void setLightTime(long value) {
			this.lightTime = value;
		}
		
		private long darkTime;
		
		public long getDarkTime() {
			return darkTime;
		}
		
		public void setDarkTime(long value) {
			this.darkTime = value;
		}
		
		protected void clearEvents() {
			begin = false;
			enterTrap = false;
			white = false;
			black = false;
		}
	}
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_Init,
		main_region_Dark,
		main_region_Light,
		main_region_Trap,
		$NullState$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[2];
	public ExampleStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setLightTime(60);
		
		sCInterface.setDarkTime(60);
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_main_region_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_Init:
				main_region_Init_react(true);
				break;
			case main_region_Dark:
				main_region_Dark_react(true);
				break;
			case main_region_Light:
				main_region_Light_react(true);
				break;
			case main_region_Trap:
				main_region_Trap_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence_main_region();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_Init:
			return stateVector[0] == State.main_region_Init;
		case main_region_Dark:
			return stateVector[0] == State.main_region_Dark;
		case main_region_Light:
			return stateVector[0] == State.main_region_Light;
		case main_region_Trap:
			return stateVector[0] == State.main_region_Trap;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public void raiseBegin() {
		sCInterface.raiseBegin();
	}
	
	public void raiseEnterTrap() {
		sCInterface.raiseEnterTrap();
	}
	
	public void raiseWhite() {
		sCInterface.raiseWhite();
	}
	
	public void raiseBlack() {
		sCInterface.raiseBlack();
	}
	
	public long getLightTime() {
		return sCInterface.getLightTime();
	}
	
	public void setLightTime(long value) {
		sCInterface.setLightTime(value);
	}
	
	public long getDarkTime() {
		return sCInterface.getDarkTime();
	}
	
	public void setDarkTime(long value) {
		sCInterface.setDarkTime(value);
	}
	
	/* Entry action for state 'Dark'. */
	private void entryAction_main_region_Dark() {
		timer.setTimer(this, 0, (1 * 1000), false);
	}
	
	/* Entry action for state 'Light'. */
	private void entryAction_main_region_Light() {
		timer.setTimer(this, 1, (1 * 1000), false);
	}
	
	/* Exit action for state 'Dark'. */
	private void exitAction_main_region_Dark() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Light'. */
	private void exitAction_main_region_Light() {
		timer.unsetTimer(this, 1);
	}
	
	/* 'default' enter sequence for state Init */
	private void enterSequence_main_region_Init_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Init;
	}
	
	/* 'default' enter sequence for state Dark */
	private void enterSequence_main_region_Dark_default() {
		entryAction_main_region_Dark();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Dark;
	}
	
	/* 'default' enter sequence for state Light */
	private void enterSequence_main_region_Light_default() {
		entryAction_main_region_Light();
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Light;
	}
	
	/* 'default' enter sequence for state Trap */
	private void enterSequence_main_region_Trap_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_Trap;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* Default exit sequence for state Init */
	private void exitSequence_main_region_Init() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Dark */
	private void exitSequence_main_region_Dark() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Dark();
	}
	
	/* Default exit sequence for state Light */
	private void exitSequence_main_region_Light() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_main_region_Light();
	}
	
	/* Default exit sequence for state Trap */
	private void exitSequence_main_region_Trap() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_Init:
			exitSequence_main_region_Init();
			break;
		case main_region_Dark:
			exitSequence_main_region_Dark();
			break;
		case main_region_Light:
			exitSequence_main_region_Light();
			break;
		case main_region_Trap:
			exitSequence_main_region_Trap();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_Init_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_Init_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.begin) {
					exitSequence_main_region_Init();
					enterSequence_main_region_Light_default();
				} else {
					if (sCInterface.enterTrap) {
						exitSequence_main_region_Init();
						enterSequence_main_region_Trap_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Dark_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.black) {
					exitSequence_main_region_Dark();
					enterSequence_main_region_Light_default();
				} else {
					if (timeEvents[0]) {
						exitSequence_main_region_Dark();
						sCInterface.setDarkTime(sCInterface.getDarkTime() - 1);
						
						enterSequence_main_region_Dark_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Light_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.white) {
					exitSequence_main_region_Light();
					enterSequence_main_region_Dark_default();
				} else {
					if (timeEvents[1]) {
						exitSequence_main_region_Light();
						sCInterface.setLightTime(sCInterface.getLightTime() - 1);
						
						enterSequence_main_region_Light_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_Trap_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
}
