/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseBegin();
		
		public void raiseEnterTrap();
		
		public void raiseWhite();
		
		public void raiseBlack();
		
		public long getLightTime();
		
		public void setLightTime(long value);
		
		public long getDarkTime();
		
		public void setDarkTime(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
